name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Updated to v3
        with:
          distribution: 'temurin'  # Updated from 'adopt'
          java-version: '17'

      - name: Build cab-book-driver
        working-directory: cab-book-driver
        run: mvn -B package

      - name: Build cab-book-user
        working-directory: cab-book-user
        run: mvn -B package
